class AppTexts {
  static const Map<String, Map<String, String>> _localizedValues = {
    'es': {
      'configuracion': 'Configuración',
      'modo_oscuro': 'Modo Oscuro',
      'alto_contraste': 'Alto Contraste',
      'idioma': 'Idioma',
      'mapa': 'Mapa',
      'publicaciones': 'Publicaciones',
      'lista': 'Lista',
      'totes': 'Todas',
      'propers': 'Cercanos',
      'edificis_distancia': 'Edificaciones ordenadas por distancia',
      'localitzacio_actualitzada': '¡Localización actualizada!',
      'sense_publicacio': 'Sin publicación',
      'fitxa_tecnica': 'FICHA TÉCNICA',
      'descripcio': 'DESCRIPCIÓN',
      'arquitectes': 'Arquitectos',
      'usos': 'Usos',
      'veure_mapa': 'Ver en el mapa',
      'llegenda_icones': 'Leyenda de iconos',
    },
    'en': {
      'configuracion': 'Settings',
      'modo_oscuro': 'Dark Mode',
      'alto_contraste': 'High Contrast',
      'idioma': 'Language',
      'mapa': 'Map',
      'publicaciones': 'Publications',
      'lista': 'List',
      'totes': 'All',
      'propers': 'Nearby',
      'edificis_distancia': 'Buildings ordered by distance',
      'localitzacio_actualitzada': 'Location updated!',
      'sense_publicacio': 'No publication',
      'fitxa_tecnica': 'TECHNICAL SPECIFICATIONS',
      'descripcio': 'DESCRIPTION',
      'arquitectes': 'Architects',
      'usos': 'Uses',
      'veure_mapa': 'View on map',
      'llegenda_icones': 'Icons legend',
    },
    'ca': {
      'configuracion': 'Configuració',
      'modo_oscuro': 'Mode Fosc',
      'alto_contraste': 'Alt Contrast',
      'idioma': 'Idioma',
      'mapa': 'Mapa',
      'publicaciones': 'Publicacions',
      'lista': 'Llista',
      'totes': 'totes',
      'propers': 'Propers',
      'edificis_distancia': 'Edificacions ordenades per distància',
      'localitzacio_actualitzada': 'Localització actualitzada!',
      'sense_publicacio': 'Sense publicació',
      'fitxa_tecnica': 'FITXA TÈCNICA',
      'descripcio': 'DESCRIPCIÓ',
      'arquitectes': 'Arquitectes',
      'usos': 'Usos',
      'veure_mapa': 'Veure al mapa',
      'llegenda_icones': "Llegenda d'icones",
    },
  };

  static String getText(String languageCode, String key) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
}